#!/bin/sh

#

normal="\033[0m"

fgblack="\033[30m"
fgred="\033[31m"
fggreen="\033[32m"
fgyellow="\033[33m"
fgblue="\033[34m"
fgviolet="\033[35m"
fgcyan="\033[36m"
fgwhite="\033[37m"
fgswitch="\033[38m"
fgreset="\033[39m"

bgblack="\033[40m"
bgred="\033[41m"
bggreen="\033[42m"
bgyellow="\033[43m"
bgblue="\033[44m"
bgviolet="\033[45m"
bgcyan="\033[46m"
bgwhite="\033[47m"
bgswitch="\033[48m"
bgreset="\033[49m"

brighton="\033[1m"
brightoff="\033[22m"

reverseon="\033[7m"
reverseoff="\033[27m"

# EOF
